### ISSUE TITLE
[Question] Can't compile a C program if include <math.h> library  

### ISSUE THREAD

**Issue by anubhabmondalDirac** [judge0/judge0#283] opened 2021-06-09 09:54 UTC
HI sir,
I implement judge0 in docker. In docker, I am using c version 9.0.1 and 10.0.1. In my code, if I include <math.h> and use any math function I am getting a compile-time error.
**Code:**
```
#include <math.h>
#include <stdio.h>

int main() {
   double number, squareRoot;

   printf("Enter a number: ");
   scanf("%lf", &number);

   // computing the square root
   squareRoot = sqrt(number);

   printf("Square root of %.2lf =  %.2lf", number, squareRoot);

   return 0;
}

```
**Error**:
```
﻿﻿﻿/usr/bin/ld: /tmp/main-7d2ec3.o: in function `main':
main.c:(.text+0x41): undefined reference to `sqrt'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

 Is there any way to run a C program with <math.h> library? @mejibyte @cesar @vvalchev @hermanzdosilovic 
Thanks in advance!

**Comment by hermanzdosilovic** [comment] 2021-06-09 10:01
Duplicate of https://github.com/judge0/judge0/issues/203.

Add `-lm` to `compiler_options`. Search for **_Options for the compiler_** in the docs (https://ce.judge0.com/).

**Closed by hermanzdosilovic** 2021-06-09 10:01 UTC
